// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';

export function GetAggregate(arg1:string,arg2:number):Promise<Array<storage.AggregationItem>>;

export function GetRecentEvents(arg1:number):Promise<Array<storage.TokenEvent>>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSummary(arg1:number):Promise<main.SummaryStats>;

export function GetTimeSeries(arg1:number):Promise<Array<storage.TimeSeriesPoint>>;

export function OpenCACert():Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;
