// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAggregate(arg1, arg2) {
  return window['go']['main']['App']['GetAggregate'](arg1, arg2);
}

export function GetAnomalies(arg1) {
  return window['go']['main']['App']['GetAnomalies'](arg1);
}

export function GetAnomalyStats(arg1) {
  return window['go']['main']['App']['GetAnomalyStats'](arg1);
}

export function GetAPIKeyMonitorStats() {
  return window['go']['main']['App']['GetAPIKeyMonitorStats']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRecentEvents(arg1) {
  return window['go']['main']['App']['GetRecentEvents'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetTimeSeries(arg1) {
  return window['go']['main']['App']['GetTimeSeries'](arg1);
}

export function GetTrend(arg1, arg2) {
  return window['go']['main']['App']['GetTrend'](arg1, arg2);
}

export function GetVerificationStats() {
  return window['go']['main']['App']['GetVerificationStats']();
}

export function DiagnoseProxy() {
  return window['go']['main']['App']['DiagnoseProxy']();
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function OpenCACert() {
  return window['go']['main']['App']['OpenCACert']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function RemoveProxyAndCert() {
  return window['go']['main']['App']['RemoveProxyAndCert']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetupProxyAndCert() {
  return window['go']['main']['App']['SetupProxyAndCert']();
}
