// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAggregate(arg1, arg2) {
  return window['go']['main']['App']['GetAggregate'](arg1, arg2);
}

export function GetRecentEvents(arg1) {
  return window['go']['main']['App']['GetRecentEvents'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetTimeSeries(arg1) {
  return window['go']['main']['App']['GetTimeSeries'](arg1);
}

export function OpenCACert() {
  return window['go']['main']['App']['OpenCACert']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}
