// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';

export function GetAPIKeyMonitorStats():Promise<main.APIKeyMonitorStats>;

export function GetAggregate(arg1:string,arg2:number):Promise<Array<storage.AggregationItem>>;

export function GetAnomalies(arg1:number):Promise<Array<storage.TokenEvent>>;

export function GetAnomalyStats(arg1:number):Promise<storage.AnomalyStats>;

export function GetLanguage():Promise<main.LanguageInfo>;

export function GetRecentEvents(arg1:number):Promise<Array<storage.TokenEvent>>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSummary(arg1:number):Promise<main.SummaryStats>;

export function GetTimeSeries(arg1:number):Promise<Array<storage.TimeSeriesPoint>>;

export function GetTrend(arg1:number,arg2:string):Promise<Array<storage.TrendPoint>>;

export function GetVerificationStats():Promise<main.VerificationStats>;

export function OpenCACert():Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<main.LanguageInfo>;
